name: "Setup Poetry"

inputs:
  key-base:
    required: true
  use-pipx:
    required: true
  use-specific-python-version:
    required: true
  specific-python-version:
    required: false

runs:
  using: "composite"
  steps:
    - run: pipx install poetry
      if: inputs.use-pipx == 'true'
    - run: pip install poetry
      if: inputs.use-pipx == 'false'
    - run: poetry config --local virtualenvs.in-project true
    - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
      id: poetry-version
    - uses: actions/cache@v3
      id: cache-poetry
      with:
        path: .venv
        key: ${{ key-base }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
    - run: poetry env use python${{ inputs.specific-python-version }}
      if: inputs.use-specific-python-version == 'true' && steps.cache-poetry.outputs.cache-hit != 'true'
    - run: poetry install
      if: steps.cache-poetry.outputs.cache-hit != 'true'
