name: "Make and upload artifacts"

inputs:
  make-binary:
    required: true

runs:
  using: "composite"
  steps:
    - run: make distribute-binary
      shell: bash
      if: inputs.make-binary == 'true'
    - run: make distribute-source
      shell: bash
      if: inputs.make-binary == 'false'
    - uses: actions/upload-artifact@v2
      with:
        path: |
          dist/*.tar.gz
          dist/*.whl
