name: "Make and upload artifacts"

inputs:
  make-binary:
    required: true
  path:
    required: false
    default: dist/

runs:
  using: "composite"
  steps:
    - run: make distribute-binary
      shell: bash
      if: inputs.make-binary == 'true'
    - run: make distribute-source
      shell: bash
      if: inputs.make-binary == 'false'
    - uses: actions/upload-artifact@v2
      with:
        path: |
          ${{ inputs.path }}*.tar.gz
          ${{ inputs.path }}*.whl
