name: Build for GNU/Linux targets

on:
  - push
#  - create
#    ref_type: tag

env:
  py_versions:
    - [3, 7]
    - [3, 8]
    - [3, 9]
    - [3, 10]

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - manylinux2014
          - manylinux_2_24
        image-arch:
          - x86_64
        py-version: ${{ py_versions }}
    env:
      image-name-full: ${{ matrix.image-name }}_${{ matrix.image-arch }}
      py-version-str: ${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}
    container:
      image: quay.io/pypa/${{ env.image-name-full }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: pipx install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: ${{ env.image-name-full }}-py${{ env.py-version-str }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry config --local virtualenvs.in-project true
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry env use python${{ env.py-version-str }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: make test
