name: Build for GNU/Linux targets

on:
  - push
#  - create
#    ref_type: tag

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - [3, 7]
          - [3, 8]
          - [3, 9]
          - [3, 10]
        image-name:
          - manylinux2014
          - manylinux_2_24
        image-arch:
          - [x86_64, 1]
    container:
      image: quay.io/pypa/${{ matrix.image-name }}_${{ matrix.image-arch[0] }}
      env:
        PYTHON_VERSION: ${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}
        IS_64: ${{ matrix.image-arch[1] }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: bash ci_build.sh
