name: Test and build

on:
  - push
#  - create
#    ref_type: tag

env:
  PY_VERSIONS_STR: >-
    ["3.7", "3.8", "3.9", "3.10"]
  VERSIONS_LINUX_STR: >-
    ["manylinux2014", "manylinux_2_24"]
  VERSIONS_MACOS_STR: >-
    ["macos-10.15", "macos-11"]
  VERSIONS_WINDOWS_STR: >-
    ["windows-2019"]


jobs:
  pass-env:
    runs-on: ubuntu-latest
    outputs:
      py-versions-str: ${{ steps.set-env.outputs.py-versions-str }}
      versions-linux-str: ${{ steps.set-env.outputs.versions-linux-str }}
      versions-macos-str: ${{ steps.set-env3.outputs.versions-macos-str }}
      versions-windows-str: ${{ steps.set-env4.outputs.versions-windows-str }}
    steps:
      - id: set-env
        run: |
          echo "::set-output name=py-versions-str::${{ env.PY_VERSIONS_STR }}"
          echo "::set-output name=versions-linux-str::${{ env.VERSIONS_LINUX_STR }}"
      - id: set-env3
        run: |
          echo "::set-output name=versions-macos-str::${{ env.VERSIONS_MACOS_STR }}"
      - id: set-env4
        run: |
          echo "::set-output name=versions-windows-str::${{ env.VERSIONS_WINDOWS_STR }}"
  build-linux:
    needs: pass-env
    strategy:
      fail-fast: false
      matrix:
        image-name: ${{ needs.pass-env.outputs.versions-linux-str }}
        image-arch:
          - x86_64
        py-version: ${{ needs.pass-env.outputs.py-versions-str }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/${{ matrix.image-name }}_${{ matrix.image-arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: pipx install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: ${{ matrix.image-name }}_${{ matrix.image-arch }}-py${{ matrix.py-version }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry config --local virtualenvs.in-project true
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry env use python${{ matrix.py-version }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: make test
  build-macos:
    needs: pass-env
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(needs.pass-env.outputs.versions-macos-str) }}
        py-version: ${{ fromJSON(needs.pass-env.outputs.py-versions-str) }}
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py-version }}
      - run: pip install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: ${{ matrix.arch }}-py${{ matrix.py-version }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry config --local virtualenvs.in-project true
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry env use python${{ env.py-version-str }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: make test
  build-windows:
    needs: pass-env
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(needs.pass-env.outputs.versions-windows-str) }}
        py-version: ${{ fromJSON(needs.pass-env.outputs.py-versions-str) }}
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        id: cache-mingw
        with:
          path: mingw
          key: ${{ matrix.arch }}-py${{ matrix.py-version }}-mingw${{ hashFiles('mingw') }}
      - run: New-Item 'mingw' -ItemType Directory -Force | Out-Null
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: (New-Object Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-mingw-w64msvcrt-10.0.0-r3.7z', 'mingw.7z')
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: 7z x 'mingw.7z' -o'mingw' -aoa
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: $env:PATH = 'mingw\\mingw64\\bin;' + $env:PATH
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py-version }}
      - run: pip install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - run: poetry config --local virtualenvs.in-project true
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
          key: ${{ matrix.arch }}-py${{ matrix.py-version }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry run python setup.py build_ext --inplace -c mingw32
      - run: poetry run python -X dev -m unittest
