name: Test and build

on:
  - push
#  - create
#    ref_type: tag

env:
  PY_VERSIONS_STR: >-
    [[3, 7], [3, 8], [3, 9], [3, 10]]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - manylinux2014
          - manylinux_2_24
        image-arch:
          - x86_64
        py-version: ${{ fromJSON(env.PY_VERSIONS_STR) }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/${{ matrix.image-name }}_${{ matrix.image-arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: pipx install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: ${{ matrix.image-name }}_${{ matrix.image-arch }}-py${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry config --local virtualenvs.in-project true
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry env use python${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: make test
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - macos-10.15
          - macos-11
        py-version: ${{ fromJSON(env.PY_VERSIONS_STR) }}
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}
      - run: pip install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: ${{ matrix.arch }}-py${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry config --local virtualenvs.in-project true
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry env use python${{ env.py-version-str }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: make test
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - windows-2019
        py-version: ${{ fromJSON(env.PY_VERSIONS_STR) }}
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        id: cache-mingw
        with:
          path: mingw
          key: ${{ matrix.arch }}-py${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}-mingw${{ hashFiles('mingw') }}
      - run: New-Item 'mingw' -ItemType Directory -Force | Out-Null
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: (New-Object Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-mingw-w64msvcrt-10.0.0-r3.7z', 'mingw.7z')
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: 7z x 'mingw.7z' -o'mingw' -aoa
        if: steps.cache-mingw.outputs.cache-hit != 'true'
      - run: $env:PATH = 'mingw\\mingw64\\bin;' + $env:PATH
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}
      - run: pip install poetry
      - run: echo "::set-output name=v::$(poetry --version | cut -d' ' -f3)"
        id: poetry-version
      - run: poetry config --local virtualenvs.in-project true
      - uses: actions/cache@v3
        id: cache-poetry
        with:
          path: |
            ./.venv
          key: ${{ matrix.arch }}-py${{ matrix.py-version[0] }}.${{ matrix.py-version[1] }}-po${{ steps.poetry-version.outputs.v }}-lock${{ hashFiles('poetry.lock') }}
      - run: poetry install
        if: steps.cache-poetry.outputs.cache-hit != 'true'
      - run: poetry run python setup.py build_ext --inplace -c mingw32
      - run: poetry run python -X dev -m unittest
